apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wo920bzxe-go
  janus-idp.io/tekton: wo920bzxe-go
  backstage.io/kubernetes-id: wo920bzxe-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wo920bzxe-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
