apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wo920bzxe-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wo920bzxe-go 
  name: wo920bzxe-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wo920bzxe-go 
